env = Environment() # initialize the environment

env.SharedLibrary(target = "chapter_one", source = ["chapter_one.cpp"], CPPPATH = ["."])

env.SharedLibrary(target = "chapter_two", source = ["chapter_two.cpp"], CPPPATH = ["."])

env.Program(target = "chapters", source = ["main.cpp"], CPPPATH = ["."], LIBS= ["libchapter_one.so","libchapter_two.so","pthread"], LIBPATH=["."], RPATH=[".", "./build"])